# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: add-dependabot-request-to-project-t-gdev.yaml
on:
  pull_request:
    types:
      - opened
      - reopened
env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
  CREATOR: ${{ github.event.pull_request.user.login }}
jobs:
  assign_one_project:
    name: Add dependabot pull request to Senzing Gdev project
    runs-on: ubuntu-latest
    steps:
    - name: Assign pull request to project
      env:
          BOOL: ${{ contains( env.CREATOR, 'dependabot' ) }}
      uses: Senzing/github-action-add-issue-to-project@main
      if: ${{ env.BOOL == 'true' }}
      with:
        project: 'https://github.com/orgs/Senzing/projects/9'
